version: '3.8'

services:
  # db:
  #   image: postgres:16
  #   environment:
  #     POSTGRES_DB: property_manager_db
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    # depends_on:
    #   - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://172.17.0.1:5432/property_manager_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    ports:
      - "8080:8080"
    restart: always

volumes:
  postgres_data: